import type { Metadata } from "next";

import "../globals.css";





export const metadata: Metadata = {
  title: "Next App Practice",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       
      >


  


        {children}


<footer>
  <div className="footer-container">
    <div className="footer-logo">
      <h2>MyWebsite</h2>
      <p>© 2025 MyWebsite. All rights reserved.</p>
    </div>

    <div className="footer-links">
      <h3>Quick Links</h3>
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>

    <div className="footer-social">
      <h3>Follow Us</h3>
      <a href="#">🌐 Facebook</a> <br />
      <a href="#">📷 Instagram</a><br />
      <a href="#">🐦 Twitter</a>
    </div>
  </div>
</footer>



      </body>
    </html>
  );
}
